spring.application.name: dice-game

server:
  port: 9005

spring:
  datasource:
    url: jdbc:h2:mem:dice_game_db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        order_updates: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

management:
  endpoints:
    #    enabled-by-default: false
    web:
      base-path: /
  endpoint:
    info:
      enabled: false
